[project]
name = "repl-nix-interactiveqnaforparents"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "altair>=5.4.1",
    "plotly>=5.24.1",
    "streamlit>=1.40.0",
]
